model:
  _target_: src.modules.models.attention_unet.AttentionUNet
  img_ch: 3
  output_ch: 1

loss:
  _target_: "monai.losses.DiceFocalLoss"
  include_background: true
  to_onehot_y: false
  sigmoid: true

metrics:
  main:
    _target_: "torchmetrics.JaccardIndex"
    task: "binary"
    num_classes: 2
    average: "macro"
  valid_best:
    _target_: "torchmetrics.MaxMetric"
