model:
  _target_: src.modules.models.sam.SAM
  model_type: "vit_b"
  sam_checkpoint: ${paths.checkpoint_dir}/sam_vit_b_01ec64.pth

loss:
  _target_: "monai.losses.DiceLoss"
  include_background: true
  to_onehot_y: true
  sigmoid: true

metrics:
  main:
    _target_: "torchmetrics.JaccardIndex"
    task: "binary"
    num_classes: 2
    average: "macro"
  valid_best:
    _target_: "torchmetrics.MaxMetric"
