model:
  _target_: src.modules.models.transunet_original.vit_seg_modeling.VisionTransformer
  vit_name: R50-ViT-B_16
  img_size: 384
  vit_patch_size: 16
  num_classes: 1
  zero_head: false
  vis: false

loss:
  _target_: "torch.nn.BCEWithLogitsLoss"
  # include_background: true
  # to_onehot_y: false
  # sigmoid: true

metrics:
  main:
    _target_: "torchmetrics.JaccardIndex"
    task: "binary"
    num_classes: 2
    average: "macro"
  valid_best:
    _target_: "torchmetrics.MaxMetric"
