model:
  _target_: src.modules.models.unet34.Unet34
  num_classes: 1

loss:
  _target_: "monai.losses.DiceLoss"
  include_background: true
  to_onehot_y: true
  sigmoid: true

metrics:
  main:
    _target_: "torchmetrics.JaccardIndex"
    task: "binary"
    num_classes: 2
    average: "macro"
  valid_best:
    _target_: "torchmetrics.MaxMetric"
