model:
  _target_: src.modules.models.module.BaseModule
  model_name: segmentation_models_pytorch/Unet
  model_repo: null

loss:
  _target_: "torch.nn.CrossEntropyLoss"

metrics:
  main:
    _target_: "torchmetrics.JaccardIndex"
    task: "multiclass"
    num_classes: 3
  valid_best:
    _target_: "torchmetrics.MaxMetric"
