model:
  _target_: src.modules.models.unet_model.UNet
  n_channels: 3
  n_classes: 1
  bilinear: false

loss:
  _target_: "torch.nn.CrossEntropyLoss"

metrics:
  main:
    _target_: "torchmetrics.JaccardIndex"
    task: "binary"
    num_classes: 2
    average: "macro"
  valid_best:
    _target_: "torchmetrics.MaxMetric"
