model:
  _target_: src.modules.models.unet_versions.UNet_2Plus.UNet_2Plus
  in_channels: 3
  n_classes: 1
  is_ds: true

loss:
  _target_: "torch.nn.BCEWithLogitsLoss"
  # include_background: true
  # to_onehot_y: false
  # sigmoid: true

metrics:
  main:
    _target_: "torchmetrics.JaccardIndex"
    task: "binary"
    num_classes: 2
    average: "macro"
  valid_best:
    _target_: "torchmetrics.MaxMetric"
