model:
  _target_: src.modules.models.unet_versions.UNet.UNet
  in_channels: 3
  n_classes: 3

loss:
  _target_: "monai.losses.GeneralizedDiceLoss"
  include_background: true
  to_onehot_y: true
  softmax: true

metrics:
  main:
    _target_: "torchmetrics.JaccardIndex"
    task: "multiclass"
    num_classes: 3
    average: "macro"
  valid_best:
    _target_: "torchmetrics.MaxMetric"
