# @package _global_

defaults:
  - _self_
  - datamodule: polyp.yaml
  - module: polyp_segmentation.yaml
  - callbacks: segment.yaml
  - logger: wandb
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"
predict: False

tags: ["dev"]

seed: 42

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
