_target_: src.datamodules.neopolyp_datamodule.NeoPolypDataModule

datasets:
  data_dir: ${paths.data_dir}
  train_val_test_split: [0.8, 0.1, 0.1]
  seed: 42
  task: "polyp-segmentation"

transforms:
  train:
    order:
      [
        "shift_scale_rotate",
        "rgb_shift",
        "random_brightness_contrast",
        "resize",
        "normalize",
        "to_tensor",
      ]
    shift_scale_rotate:
      _target_: albumentations.ShiftScaleRotate
      shift_limit: 0.05
      scale_limit: 0.05
      rotate_limit: 15
      p: 0.5
    rgb_shift:
      _target_: albumentations.RGBShift
      r_shift_limit: 15
      g_shift_limit: 15
      b_shift_limit: 15
      p: 0.5
    random_brightness_contrast:
      _target_: albumentations.RandomBrightnessContrast
      p: 0.5
    resize:
      _target_: albumentations.Resize
      height: 512
      width: 512
      p: 1.0
    normalize:
      _target_: albumentations.Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      p: 1.0
    to_tensor:
      _target_: albumentations.pytorch.transforms.ToTensorV2
      p: 1.0

  valid_test_predict:
    order: ["resize", "normalize", "to_tensor"]
    resize:
      _target_: albumentations.Resize
      height: 512
      width: 512
      p: 1.0
    normalize:
      _target_: albumentations.Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      p: 1.0
    to_tensor:
      _target_: albumentations.pytorch.transforms.ToTensorV2
      p: 1.0

loaders:
  train:
    batch_size: 4
    shuffle: True
    num_workers: 0
    drop_last: True
    pin_memory: False

  valid:
    batch_size: 4
    shuffle: False
    num_workers: 0
    drop_last: False
    pin_memory: False

  test:
    batch_size: 4
    shuffle: False
    num_workers: 0
    drop_last: False
    pin_memory: False

  predict:
    batch_size: 4
    shuffle: False
    num_workers: 0
    drop_last: False
    pin_memory: False
